version: '3.9'
services:
  curl:
    container_name: curl
    build:
      context: .
      dockerfile: Dockerfile
    image: curl

    

#########     Kong DB       #########
  postgres:
    image: postgres:9.6-alpine
    restart: always 
    hostname: kong-database
    container_name: kong-database
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_DB: "kong"
      POSTGRES_PASSWORD: "kong"
######### Kong DB Bootstrap #########
  kong-bootstrap:
    image: kong/kong-gateway:latest
    hostname: kong-bootstrap
    container_name: kong-bootstrap
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
    command: "kong migrations bootstrap"
    restart: "on-failure"
  
#########       Kong       #########
  kong:
    image: kong/kong-gateway:latest
    restart: always 
    hostname: kong
    container_name: kong
    depends_on:
      - kong-bootstrap
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    command: "kong start"
    ports:
     - "8000:8000"
     - "8002:8002"
     - "8433:8433"
     - "8001:8001"
     - "8444:8444"

